### ISSUE TITLE
SEQUENCER IS NOT V10 READY

### ISSUE THREAD

**Issue by Haxxer** [fantasycalendar/FoundryVTT-Sequencer#99]
That's it. Don't install it on V10 foundries.

**Comment by arkangel85** [comment]
it work with alpha release

**Comment by Haxxer** [comment]
It is not recommended. I will not be held responsible for any broken worlds.

**Comment by arkangel85** [comment]
yep i installed it only in my dev server

**Comment by arkangel85** [comment]
What I don’t understand is how it is possible that a developer has not prepared a release in time despite the fact that it is more than a month that the testing versions for v10 have been published. I am also a developer and my modules are fully functional since yesterday.

**Comment by MrVauxs** [comment]
> What I don’t understand is how it is possible that a developer has not prepared a release in time despite the fact that it is more than a month that the testing versions for v10 have been published. I am also a developer and my modules are fully functional since yesterday.

People have their own lives, development cycles, and priorities. Just because you could work your modules into V10, does not make others entitled to do so. 

Some people prefer to wait till the actual release of new versions before updating their modules to support them, rather than having to update every time a new patch came out for the alpha/beta versions.

Don't be a dick.

**Comment by arkangel85** [comment]
Sorry man, I didn’t mean to be an asshole, it was just a consideration. Let me explain: you knew that this realease would bring great news and that users would want it as soon as possible, I understand that everyone also has their own life, I just say that when a person makes a commitment would be nice if he respected it. at the end prerelease has been online for a week. in any case I really admire your work with sequencer!

**Comment by zeel01** [comment]
> What I don’t understand is how it is possible that a developer has not prepared a release in time despite the fact that it is more than a month that the testing versions for v10 have been published. I am also a developer and my modules are fully functional since yesterday.
> 
> Also DAE is not ready yet, incredible...

Could be that they have other priorities beyond keeping a *free* module up to date with a moving target like Foundry versions? Or maybe, like most of us, they looked at how many times things break in updates and decided to wait for the "stable" version before spending their limited time and energy working on updating modules.

**Comment by MrVauxs** [comment]
> Sorry man, I didn’t mean to be an asshole, it was just a consideration. Let me explain: you knew that this realease would bring great news and that users would want it as soon as possible, I understand that everyone also has their own life, I just say that when a person makes a commitment would be nice if he respected it. at the end prerelease has been online for a week. in any case I really admire your work with sequencer!

There was no commitment. Nobody is entitled to your update schedule.

**Comment by BadIdeasBureau** [comment]
> I just say that when a person makes a commitment would be nice if he respected it

This is even more of an asshole comment than your previous one, tbh.  Just say sorry, and walk away, without the snarky asides.

You are directly contributing to the kind of pressures which cause us to lose great developers from the community.

**Comment by arkangel85** [comment]
ok ok sorry guys

**Comment by zeel01** [comment]
Exactly what BiB said. Modules are a *ton* of work and the vast majority of us do it without pay, for "fun" - but it gets less fun when people decide that us having the audacity to give them something for *free* means they are entitled to make demands about the schedule.

**Comment by V13Axel** [comment]
> What I don’t understand is how it is possible that a developer has not prepared a release in time despite the fact that it is more than a month that the testing versions for v10 have been published. I am also a developer and my modules are fully functional since yesterday.

FTFY:

> "What I don't understand is how it is possible that ~~a developer has not prepared a release in time~~ you didn't work for 
**my** needs, for free! ~~I am also a developer and my modules are fully functional since yesterday~~ I worked for **my** needs, for free!"

Nobody has committed to anything. Sequencer is provided as-is, for free, and you always use it at your own risk. As is basically the case with _any_ open source software.

@arkangel85 I don't see any noteworthy repositories on your Github account nor your GitLab account, would **definitely** love to see all the cool stuff you've developed and rigorously kept up-to-date🙂. Maybe you should show us **your** hugely popular, community-loved, entirely up-to-date, hundreds-of-lines-of-code, modules present on 25% of all Forge-VTT installs that contain and provide **lots** of varying functionality, that you had all the free time in the world to update real quick and easy like, and then we can all bow down at your greatness for being an amazing 10X developer?🙃

I realize you've already deleted your original comment - Good on you, I was just a few minutes shy of deciding to do that myself. However, I couldn't sit by and not jump in here to address one of my biggest pet peeves: Demanding that people work on something, for free, that they are giving away for free, because it inconvenienced **you** that they didn't do so.

The beauty, mister "I'm also a developer", is that sequencer is open source. If you want it updated yesterday, open a PR and update it yesterday. Otherwise, you can go away, be patient, and wait until @Haxxer is done coughing up half a lung with COVID-19 to maybe see V10 support when he gets around to it.

**Comment by arkangel85** [comment]
> > What I don’t understand is how it is possible that a developer has not prepared a release in time despite the fact that it is more than a month that the testing versions for v10 have been published. I am also a developer and my modules are fully functional since yesterday.
> 
> FTFY:
> 
> > "What I don't understand is how it is possible that ~a developer has not prepared a release in time~ you didn't work for
> > **my** needs, for free! ~I am also a developer and my modules are fully functional since yesterday~ I worked for **my** needs, for free!"
> 
> Nobody has committed to anything. Sequencer is provided as-is, for free, and you always use it at your own risk. As is basically the case with _any_ open source software.
> 
> @arkangel85 I don't see any noteworthy repositories on your Github account nor your GitLab account, would **definitely** love to see all the cool stuff you've developed and rigorously kept up-to-date🙂. Maybe you should show us **your** hugely popular, community-loved, entirely up-to-date, hundreds-of-lines-of-code, modules present on 25% of all Forge-VTT installs that contain and provide **lots** of varying functionality, that you had all the free time in the world to update real quick and easy like, and then we can all bow down at your greatness for being an amazing 10X developer?🙃
> 
> I realize you've already deleted your original comment - Good on you, I was just a few minutes shy of deciding to do that myself. However, I couldn't sit by and not jump in here to address one of my biggest pet peeves: Demanding that people work on something, for free, that they are giving away for free, because it inconvenienced **you** that they didn't do so.
> 
> The beauty, mister "I'm also a developer", is that sequencer is open source. If you want it updated yesterday, open a PR and update it yesterday. Otherwise, you can go away, be patient, and wait until @Haxxer is done coughing up half a lung with COVID-19 to maybe see V10 support when he gets around to it.

I have already apologized because you are right, I did not think that your modules were free and it is equally true that mine do not appeal to a huge audience like yours.  so I repeat my apologies again and go further

**Comment by V13Axel** [comment]
All good @arkangel85 - Go ye forth and teach all nations
